import type { DocLink } from "@/shared/ui/docs-card";

export const SVEDENIYA_DOCUMENTS = {
  title: "Документы",
  docs: [
    { label: "Приказ об утверждении ЛНА", kind: "pdf", href: "https://disk.yandex.ru/i/x44m_xjgqFxYhw" },
    { label: "1.4 Положение о нормах проф этики педагогических работников", kind: "pdf", href: "https://disk.yandex.ru/i/-WTektieBllj6A" },
    { label: "1.4 Положение о нормах проф этики педагогических работников", kind: "sign", href: "https://disk.yandex.ru/d/NLODjoBKcKLFZQ" },
    { label: "1.5 Положение о порядке предоставления МТО", kind: "pdf", href: "https://disk.yandex.ru/i/JTj7IQAYXIFq3w" },
    { label: "1.5 Положение о порядке предоставления МТО", kind: "sign", href: "https://disk.yandex.ru/d/c55iYIkLKo1Xtg" },
    { label: "1.6 Положение о порядке бесплатного пользования педагогическими, методическими и научными услугами", kind: "pdf", href: "https://disk.yandex.ru/i/i2YYPH8DqY1cig" },
    { label: "1.6 Положение о порядке бесплатного пользования педагогическими, методическими и научными услугами", kind: "sign", href: "https://disk.yandex.ru/d/S29uT_xPWJ_-VQ" },
    { label: "1.7 Положение о режиме рабочего времени педагогических работников", kind: "pdf", href: "https://disk.yandex.ru/i/5m4oiLDOR24q9w" },
    { label: "1.7 Положение о режиме рабочего времени педагогических работников", kind: "sign", href: "https://disk.yandex.ru/d/j0morVUQz3wkBg" },
    { label: "1.8 Положение о соотношении учебной и другой пед работы", kind: "pdf", href: "https://disk.yandex.ru/i/4IU599r6ptt7cQ" },
    { label: "1.8 Положение о соотношении учебной и другой пед работы", kind: "sign", href: "https://disk.yandex.ru/d/dySX0biLBDDZCQ" },
    { label: "2.1 Правила внутреннего трудового распорядка", kind: "pdf", href: "https://disk.yandex.ru/i/kFSEqp1f1pT-Vg" },
    { label: "2.1 Правила внутреннего трудового распорядка", kind: "sign", href: "https://disk.yandex.ru/d/7_boru9doYq9FQ" },
    { label: "2.10 Положение о внутренней системе оценки качества образования", kind: "pdf", href: "https://disk.yandex.ru/i/swe45InHnGh6IA" },
    { label: "2.10 Положение о внутренней системе оценки качества образования", kind: "sign", href: "https://disk.yandex.ru/d/dgLTRzL8q22ksQ" },
    { label: "2.11. Положение о совете обучающихся", kind: "pdf", href: "https://disk.yandex.ru/i/2W_9-lQHuyqDCw" },
    { label: "2.11. Положение о совете обучающихся", kind: "sign", href: "https://disk.yandex.ru/d/5tJfuE3rGwJVqg" },
    { label: "2.12. Положение о рабочей группе по противодействию и предотвращению коррупции", kind: "pdf", href: "https://disk.yandex.ru/i/1cYFG-lbex8azg" },
    { label: "2.12. Положение о рабочей группе по противодействию и предотвращению коррупции", kind: "sign", href: "https://disk.yandex.ru/d/p5w7fY8GCjVprg" },
    { label: "2.14 О порядке хранения в архивах", kind: "pdf", href: "https://disk.yandex.ru/i/FGTiqrP4ImM-UA" },
    { label: "2.14 О порядке хранения в архивах", kind: "sign", href: "https://disk.yandex.ru/d/mrEotRFHMVq4wA" },
    { label: "2.16. Положение о порядке пользования учебными пособиями", kind: "pdf", href: "https://disk.yandex.ru/i/oS7TDRviyAfcnA" },
    { label: "2.16. Положение о порядке пользования учебными пособиями", kind: "sign", href: "https://disk.yandex.ru/d/ugjNIDhLsTrs5g" },
    { label: "2.17 Положение об информационной открытости и официальном сайте", kind: "pdf", href: "https://disk.yandex.ru/i/g9Uv1EhW-Y93mw" },
    { label: "2.17 Положение об информационной открытости и официальном сайте", kind: "sign", href: "https://disk.yandex.ru/d/b6Ip___qN7caFg" },
    { label: "2.18 Положение о комиссии по регулированию споров между участниками образовательных отношений", kind: "pdf", href: "https://disk.yandex.ru/i/MFBMYwqVFc-51g" },
    { label: "2.18 Положение о комиссии по регулированию споров между участниками образовательных отношений", kind: "sign", href: "https://disk.yandex.ru/d/8MlxCj7ihDenpA" },
    { label: "2.19 Положение о конфликте интересов", kind: "pdf", href: "https://disk.yandex.ru/i/VWg1-7Swd4xMxA" },
    { label: "2.19 Положение о конфликте интересов", kind: "sign", href: "https://disk.yandex.ru/d/y2TBcfXUeJJKhw" },
    { label: "2.20 Положение об обработке персональных данных", kind: "pdf", href: "https://disk.yandex.ru/i/Sk3Z3vv6qUHfoA" },
    { label: "2.20 Положение об обработке персональных данных", kind: "sign", href: "https://disk.yandex.ru/d/GhUiqLOzPNjk0g" },
    { label: "2.21 Положение о порядке рассмотрения обращений граждан", kind: "pdf", href: "https://disk.yandex.ru/i/6A7yVDqIRDDZ9A" },
    { label: "2.21 Положение о порядке рассмотрения обращений граждан", kind: "sign", href: "https://disk.yandex.ru/d/iPBC_rDpUjCoaw" },
    { label: "2.22 Положение об ЭО и ДОТ", kind: "pdf", href: "https://disk.yandex.ru/i/DtsjE5H4u9pXkg" },
    { label: "2.22 Положение об ЭО и ДОТ", kind: "sign", href: "https://disk.yandex.ru/d/risy-CekxDjxOg" },
    { label: "2.23 Публичная оферта на заключение договора для получения", kind: "pdf", href: "https://disk.yandex.ru/i/NjlxDsY8faoQ9Q" },
    { label: "2.23 Публичная оферта на заключение договора для получения", kind: "sign", href: "https://disk.yandex.ru/d/IRTnE_9rDOYZlQ" },
    { label: "2.2 Правила внутреннего распорядка обучающихся", kind: "pdf", href: "https://disk.yandex.ru/i/cIbTH3lOIzKaXg" },
    { label: "2.2 Правила внутреннего распорядка обучающихся", kind: "sign", href: "https://disk.yandex.ru/d/JKK0ecBMGpd2zg" },
    { label: "2.3 Правила приема обучающихся", kind: "pdf", href: "https://disk.yandex.ru/i/WvNQjX4NAqXmSw" },
    { label: "2.3 Правила приема обучающихся", kind: "sign", href: "https://disk.yandex.ru/d/kYjBDkUFUOgd0A" },
    { label: "2.4 Положение о режиме занятий обучающихся и формах обучения", kind: "pdf", href: "https://disk.yandex.ru/i/R-7_CNrRtjYtvA" },
    { label: "2.4 Положение о режиме занятий обучающихся и формах обучения", kind: "sign", href: "https://disk.yandex.ru/d/G66PR5PazKg0nQ" },
    { label: "2.5 Об обучении по индивидуальному учебному плану", kind: "pdf", href: "https://disk.yandex.ru/i/qR8mwRfeUAS6Vw" },
    { label: "2.5 Об обучении по индивидуальному учебному плану", kind: "sign", href: "https://disk.yandex.ru/d/gZTXYxZzXNH_wA" },
    { label: "2.6 Положение о текущем контроле промежуточном контроле, итоговой аттестации", kind: "pdf", href: "https://disk.yandex.ru/i/Kknhc5g8TtBUJw" },
    { label: "2.6 Положение о текущем контроле промежуточном контроле, итоговой аттестации", kind: "sign", href: "https://disk.yandex.ru/d/wdLbREjzxAhBjQ" },
    { label: "2.7 Положение о порядке перевода, отчисления, восстановления", kind: "pdf", href: "https://disk.yandex.ru/i/oNdtU2_bivpSww" },
    { label: "2.7 Положение о порядке перевода, отчисления, восстановления", kind: "sign", href: "https://disk.yandex.ru/d/QNqPf0CPqIGLqA" },
    { label: "2.8 Порядок оформления возникновения, приостановления и прекращения отношений между образовательной организацией и обучающимися", kind: "pdf", href: "https://disk.yandex.ru/i/gZGMdIjzN5cT9Q" },
    { label: "2.8 Порядок оформления возникновения, приостановления и прекращения отношений между образовательной организацией и обучающимися", kind: "sign", href: "https://disk.yandex.ru/d/McG5LsFptd03Qg" },
    { label: "2.9 Положение о порядке проведения самообследования", kind: "pdf", href: "https://disk.yandex.ru/i/hDzXgFpCV2KnUg" },
    { label: "2.9 Положение о порядке проведения самообследования", kind: "sign", href: "https://disk.yandex.ru/d/gKgTzvPtvcY7mw" },
    { label: "3.1 Положение об языке обучения", kind: "pdf", href: "https://disk.yandex.ru/i/OlsC7avON_oRvg" },
    { label: "3.1 Положение об языке обучения", kind: "sign", href: "https://disk.yandex.ru/d/Agf5lR_QsVJRrQ" },
    { label: "4 ИНН ОГРН Недра", kind: "sign", href: "https://disk.yandex.ru/d/lDNmCBhjFQO1yg" },
    { label: "4.1 Положение о порядке предоставления платных образовательных услуг", kind: "pdf", href: "https://disk.yandex.ru/i/3wZr37vJhZNHlw" },
    { label: "4.1 Положение о порядке предоставления платных образовательных услуг", kind: "sign", href: "https://disk.yandex.ru/d/jyjlfBDiNDf3lw" },
    { label: "4.2 Приказ о стоимости", kind: "pdf", href: "https://disk.yandex.ru/i/_DBePwhR84XX-A" },
    { label: "4.2 Приказ о стоимости", kind: "sign", href: "https://disk.yandex.ru/d/hMlSJ_OF7rm8bw" },
    { label: "4.3 Положение об основаниях и порядке снижения стоимости платных образовательных услуг", kind: "pdf", href: "https://disk.yandex.ru/i/S396Xu7bZ6PIaA" },
    { label: "4.3 Положение об основаниях и порядке снижения стоимости платных образовательных услуг", kind: "sign", href: "https://disk.yandex.ru/d/3Q35UnxHT7Oeyw" },
    { label: "Приказ об утверждении ЛНА", kind: "sign", href: "https://disk.yandex.ru/d/7U1xkgVhd5cfHw" },
  ] as DocLink[],
};
